In [1]:
import pandas as pd

In [20]:
df_t5 = pd.read_csv("data/generated_summaries/T5_summary_output.csv")
df_t5

,text,summary,id,generated_summaries
0,"Prison Link Cymru had 1,099 referrals in 2015-...","There is a ""chronic"" need for more housing for...",38264402,Thousands of people were killed when the tsuna...
1,Officers searched properties in the Waterfront...,"A man has appeared in court after firearms, am...",34227252,Stoke City have signed Cameroon midfielder Eri...
2,"Jordan Hill, Brittany Covington and Tesfaye Co...",Four people accused of kidnapping and torturin...,38537698,A man who sent police a selfie of himself with...
3,The 48-year-old former Arsenal goalkeeper play...,West Brom have appointed Nicky Hammond as tech...,36175342,The Irish embassy in Washington has expressed ...
4,Restoring the function of the organ - which he...,The pancreas can be triggered to regenerate it...,39070183,A former home of author John Fowles has been r...
...,...,...,...,...
11329,Amnesty International supporters are zipped in...,Two hundred body bags have been placed on Brig...,32411431,A Dutch submarine has been tracked by two anti...
11330,The project was launched in Grenada by the pri...,Budding hospitality workers from the Caribbean...,38139638,Michael Pollock won his first race since the R...
11331,The world number two won 6-2 6-0 in 66 minutes...,Britain's Andy Murray is through to the Monte ...,36054448,A group of students from Eindhoven University ...
11332,Mr Pistorius says he mistakenly shot his girlf...,A forensics expert has swung a cricket bat at ...,26541765,Mental health patients in England are being di...
11333,Media playback is unsupported on your device\n...,Martin went to the German Occupation Museum to...,32607891,The South Wales Police force area has elected ...

In [ ]:
df_bart = pd.read_csv("data/generated_summaries/bart_summary_output.csv")
df_bart